### ISSUE TITLE
Use the GPR result of vsetvl

### ISSUE THREAD

**Issue by rkruppe** [rkruppe/rvv-llvm#3]
At the Machine IR level, VSETVL[_ic] defines two regs, one GPR and VLR. Both hold the same value, they just represent the fact that VSETVL both changes the vector length and returns the new vector length in a GPR. The corresponding IR intrinsic has (and should have) only one return value, instruction selection (in RISCVISelLowering.cpp) identifies this result with the VLR result and the GPR result remains unused. This causes unnecessary copies between GPRs and VL: doing arithmetic with the result of the setvl intrinsic emits code to read back VL instead of just using the GPR result.

This could be fixed in a MIR optimization pass running after instruction selection. It should look for `COPY` instructions with a (virtreg) VLR source and (virtreg) GPR destination, where the source comes from a VSETVL[_ic] instruction. Uses of that copy can be replaced with the GPR output of the setvl instruction, which avoids the CSR read.

**Comment by pranav-prakash** [comment]
I'm taking a look at this, and so far implemented the skeleton of a machine function pass. 

By this point I believe the DAG is destroyed and everything is linearized (but still in ssa form), so my idea was to iterate through all the machine instructions twice, first building a map from `<vlr, gpr>` where each entry is the result of a `VSETVL` operation, then create another map for `<reg, gpr>` with an entry for each `copy` instruction that copies from the `vlr` to a virtual reg. Then we can delete the `copy` and replace all uses of the `reg` from the `COPY` with the corresponding gpr from the `vsetvl`.

Is this a good way of going about it, or is there some other way to directly determine the source of an operand?

Additionally, in a case like 

```
%vl = call i32 @llvm.riscv.setvl(i32 99)
ret i32 %vl
```

it seems that llvm performs some ABI specific register allocation even before the machine pass:

```
bb.0 (%ir-block.0):
  %0:gpr = ADDI $x0, 99
  %1:vlr, %2:gpr = VSETVL_ic killed %0:gpr
  $x10 = COPY %1:vlr
  PseudoRET implicit $x10
```
in these cases should we skip the replacement if the operand we are replacing is a physical register instead of a virtual one (since otherwise wouldn't we violate the ABI).

**Comment by rkruppe** [comment]
> Is this a good way of going about it, or is there some other way to directly determine the source of an operand?

MachineRegisterInfo (`MF.getRegInfo()`) already has all the information to give you the MachineInstr that defines a virtual register, as well as all uses of the COPY.

> it seems that llvm performs some ABI specific register allocation even before the machine pass:

Argument passing and return details are picked during ISel, yeah. Though note that these copies out of / into physregs really only mean the value needs to be in that physical register *at this point in time*, regalloc still has total freedom about how it allocates registers at other times (though of course it's often beneficial to "go with the flow" to avoid copies).

> in these cases should we skip the replacement if the operand we are replacing is a physical register instead of a virtual one (since otherwise wouldn't we violate the ABI).

Hm yeah, good point. However, while we can't turn this into `PseudoRET implicit %2:gpr`, we should at least replace the operand of the COPY, i.e., turn the COPY into `$x10 = COPY %2:gpr`. That would again enable us to to get this instruction sequence:

```
addi t0, x0, 99
vsetvl a0, t0
```

... instead of reading back VL via a csrr.

Actually, come to think of it, we don't really need to mess with the *uses* of the VL->GPR copy, we can just always turn `gpr = COPY %i:vlr` into `gpr = COPY %j:gpr` and let register coalescing clean up the cases where the destination is a virtual register.
